#!/usr/bin/env php
<?php
/**
 * DESMG Telegram Bot
 * Copyright (C) 2023 DESMG
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

use Symfony\Component\Console\Input\ArgvInput;

if (PHP_MAJOR_VERSION != 8 || PHP_MINOR_VERSION != 3) {
    echo "PHP Version Mismatch\n";
    exit(130);
}

define('LARAVEL_START', (new DateTime())->format('U.u'));

require __DIR__ . '/vendor/autoload.php';
$status = (require_once __DIR__ . '/bootstrap/app.php')->handleCommand(new ArgvInput);
exit($status);
