#!/usr/bin/env php
<?php
/**
 * DESMG Telegram Bot
 * This file is a part of our Open Source Project (https://github.com/jyxjjj/Telegram-Bot)
 *
 * @copyright 2015-2024 DESMG Co., Ltd.
 * @license GNU General Public License v3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
 * @author DESMG Co., Ltd. (www.desmg.com) < opensource@desmg.org >
 *
 * @QQ 773933146
 * @Telegram jyxjjj (https://t.me/jyxjjj)
 * @Producer DESMG
 *
 * Copyright (C) 2015-2024 DESMG
 * All Rights Reserved.
 *
 * 🇨🇳 🇬🇧 🇳🇱
 * Terms of Service: https://www.desmg.com/policies/terms
 *
 * Released under GNU General Public License Version 3.0
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

echo <<<GPL
    DESMG Telegram Bot Copyright (C) 2023 DESMG
    This program comes with ABSOLUTELY NO WARRANTY; for details see `LICENSE' file.
    This is free software, and you are welcome to redistribute it
    under certain conditions; for details see `LICENSE' file.

GPL;

use Symfony\Component\Console\Input\ArgvInput;

if (PHP_MAJOR_VERSION != 8 || PHP_MINOR_VERSION != 3) {
    echo "PHP Version Mismatch\n";
    exit(130);
}

define('LARAVEL_START', (new DateTime())->format('U.u'));

require __DIR__ . '/vendor/autoload.php';
$status = (require_once __DIR__ . '/bootstrap/app.php')->handleCommand(new ArgvInput);
exit($status);
