#!/usr/bin/env php
<?php

if (PHP_MAJOR_VERSION != 8 || PHP_MINOR_VERSION != 2) {
    echo "PHP Version Mismatch\n";
    exit(130);
}

define('LARAVEL_START', microtime(true));
require __DIR__ . '/vendor/autoload.php';

use Illuminate\Contracts\Console\Kernel;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Kernel::class);
$status = $kernel->handle(
    $input = new ArgvInput,
    new ConsoleOutput
);
$kernel->terminate($input, $status);
exit($status);
