version: '3.9'
services:
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        environment:
            - TZ=Etc/GMT-8
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 5s
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
            - net.ipv4.conf.all.rp_filter=0
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.default.arp_announce=2
            - net.ipv4.conf.lo.arp_announce=2
            - net.ipv4.conf.all.arp_announce=2
            - net.ipv4.tcp_max_tw_buckets=5000
            - net.ipv4.tcp_syncookies=1
            - net.ipv4.tcp_max_syn_backlog=2048
            - net.core.somaxconn=51200
            - net.ipv4.tcp_synack_retries=2
            - net.ipv4.tcp_fastopen=3
        dns:
            - 1.1.1.1
            - 8.8.8.8
            - 8.8.4.4
            - 223.5.5.5
            - 223.6.6.6
        ports:
            -   target: 3306
                published: 3306
                protocol: tcp
                mode: host
        volumes:
            -   type: bind
                source: /www/server/mariadb/data/
                target: /var/lib/mysql/
            -   type: bind
                source: /www/server/mariadb/mysql/
                target: /etc/mysql/
        healthcheck:
            disable: true
    redis:
        container_name: redis
        image: redis:latest
        environment:
            - TZ=Etc/GMT-8
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 5s
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
            - net.ipv4.conf.all.rp_filter=0
            - net.ipv4.conf.default.rp_filter=0
            - net.ipv4.conf.default.arp_announce=2
            - net.ipv4.conf.lo.arp_announce=2
            - net.ipv4.conf.all.arp_announce=2
            - net.ipv4.tcp_max_tw_buckets=5000
            - net.ipv4.tcp_syncookies=1
            - net.ipv4.tcp_max_syn_backlog=2048
            - net.core.somaxconn=51200
            - net.ipv4.tcp_synack_retries=2
            - net.ipv4.tcp_fastopen=3
        dns:
            - 1.1.1.1
            - 8.8.8.8
            - 8.8.4.4
            - 223.5.5.5
            - 223.6.6.6
        ports:
            -   target: 6379
                published: 6379
                protocol: tcp
                mode: host
        volumes:
            -   type: bind
                source: /www/server/redis/conf/
                target: /usr/local/etc/redis/
            -   type: bind
                source: /www/server/redis/data/
                target: /data/
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
        healthcheck:
            disable: true
networks:
    default:
        name: podman
        external: true
