<?php /** @noinspection PhpUnhandledExceptionInspection */

namespace App\Common\Cache;

use App\Jobs\DeleteCache;
use Closure;
use Illuminate\Support\Facades\Redis;

/**
 * <b>Do not edit this file</b>
 * @see CacheKeyEnum
 */
class CacheKey
{
    use CacheSerializable, CacheRedisHelper;

    private \Redis $connection;
    private string $prefix;
    private string $key;
    private string $fullKey;

    public function __construct(CacheKeyEnum $key, int|string ...$v)
    {
        $this->connection = Redis::connection('cache')->client();
        $this->prefix = config('database.redis.options.prefix') . config('cache.prefix') . ':';
        $this->key = vsprintf($key->value, $v);
        $this->fullKey = $this->prefix . $this->key;
    }

    public function delete(): bool
    {
        DeleteCache::dispatch($this->fullKey);
        return $this->connection->del($this->fullKey);
    }

    public function has(): bool
    {
        return $this->connection->exists($this->fullKey);
    }

    public function remember(Closure $callback, int $ttl = 300): mixed
    {
        $value = $this->get('THIS_IS_A_DEFAULT_VALUE_THAT_WILL_NEVER_BE_RETURNED_BY_ANY_FUNCTION');
        if ($value != 'THIS_IS_A_DEFAULT_VALUE_THAT_WILL_NEVER_BE_RETURNED_BY_ANY_FUNCTION') {
            return $value;
        }
        $value = $callback();
        $this->set($value, $ttl);
        return $value;
    }

    public function get($default = null): mixed
    {
        return $this->unserialize($this->connection->get($this->fullKey)) ?? $default;
    }

    public function set($value, int $ttl): bool
    {
        return $this->connection->set($this->fullKey, $this->serialize($value), $ttl);
    }
}
